# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c69f3c4b907eb70d0a4f1d60e7db9c7b824ed2c02b4210a40aaab8c0c1983fd26988085930a42d06576d5770cebd28204928f323652ff4367c322478c46cf7

test:
  secret_key_base: e4bb238d2e3358f27d378013a048443b8be9c9eabd4099c91a702ebd115e0c13b2fc9ef41716dbe1362b6938644827de2bc76737d7ab6e07f2508293cedc912b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
